# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
      
    - name: Test
      run: go test ./... -v -coverprofile=cover.out -covermode=atomic

    - name: Tool Cover
      run: go tool cover -html=cover.out -o cover.html
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
       token: ${{ secrets.CODECOV_TOKEN }}
       file: ./cover.out
       flags: unittests
       verbose: true
